<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\logo\mhw-512.ico</ApplicationIcon>
    <NoWarn>$(NoWarn);NU1902</NoWarn>

    <!-- Anti-Virus / VirusTotal Optimization -->
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <PublishReadyToRun>true</PublishReadyToRun>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.4" />
    <PackageReference Include="SharpCompress" Version="0.38.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Resource Include="Assets\**\*" />
    <Content Include="Extensions\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\logo\mhw-512.ico" Link="logo\mhw-512.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModTogether.API\ModTogether.API.csproj" />
    <ProjectReference Include="..\ModTogether.Extensions.MHW\ModTogether.Extensions.MHW.csproj" />
  </ItemGroup>

</Project>
